#Compose.yaml

services:
  # Service de l'application Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: entretien-infirmier-app
    restart: unless-stopped
    networks:
      - traefik
      - supabase_default
    env_file:
      - .env.production
    volumes:
      - app-data:/app/data
      - ./logs:/app/logs
      - ./prisma:/app/prisma
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.vital-sync.ch`)"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      #- "traefik.http.routers.app.middlewares=infomaniak-auth"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  traefik:
    external: true
  supabase_default:    # ← Ajouter cette section
    external: true

volumes:
  app-data:
    driver: local