export const POSTES = ['Agent de production', 'Cariste', "Chef d'équipe", 'Administratif'];
export const MANAGERS = ['Dupont Jean', 'Martin Sophie', 'Bernard Paul'];
export const ZONES = ['Zone A', 'Zone B', 'Zone C', 'Administration'];
export const CONTRATS = ['CDI', 'CDD', 'Intérim', 'Stage', 'Alternance'];
export const DEPARTEMENTS = ['Production', 'Logistique', 'Administration', 'Maintenance'];
export const TYPES_ENTRETIEN = ['Initial', 'Suivi', 'Reprise', 'Pré-reprise', 'Occasionnel'];
export const TAUX_ACTIVITE = ['100%', '80%', '75%', '50%', '25%'];
export const ETATS_CIVILS = ['Célibataire', 'Marié(e)', 'Pacsé(e)', 'Divorcé(e)', 'Veuf/Veuve'];
export const TYPES_TRANSPORT = ['Voiture', 'Transport en commun', 'Vélo', 'Marche', 'Deux roues motorisé'];